### ISSUE TITLE
Testen von den go-Methoden in Board

### ISSUE THREAD

**Issue by PabloMorenoUm** [PabloMorenoUm/Projekt#5]
Ordentliches Testen mit doctest.h, um sicherzustellen, dass die go-Methoden das tun, was sie tun sollen

**Comment by MoritzBecker19897** [comment]
Moritz testet Coin

**Comment by MoritzBecker19897** [comment]
Test von Board nach erfolgreichem Durchlauf @PabloMorenoUm @MoritzBecker19897
